name: Lint

on:
  pull_request:
    branches-ignore:
      - 'master'
  push:

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v4
    - uses: cachix/install-nix-action@v25
      with:
        nix_path: nixpkgs=channel:nixos-unstable
    - name: setup
      run: |
        pip install mypy
        pip install -r requirements.txt
        mypy *.py formie > /dev/null || true
        yes | mypy --install-types
    - name: run black (formatter)
      run: |
        nix develop --command bash -c "black --diff --check formie/"
    - name: run mypy
      run: |
        mypy --strict *.py formie
